
.PHONY : all
all : lib2patch derive-values install doc

.PHONY : lib2patch
# link a lib's patch.xodp to project lib-edit, patch lib-x-x-x
lib2patch :
	rm -rf ~/xod/lib-edit/lib-*; cd lib; for p in `find . -name patch.xodp`; do n=`dirname $$p | sed 's/^\.\///; s/\//-/g'`; newdir=~/xod/lib-edit/lib-$$n; mkdir -p $$newdir && ln -s `pwd`/`dirname $$p`/patch.xodp $$newdir; done

.PHONY : derive-values
derive-values : lib/awg/values/boolean lib/awg/values/number lib/awg/values/boolean/any.cpp lib/awg/values/number/any.cpp lib/awg/values/boolean/patch.xodp lib/awg/values/number/patch.xodp lib/awg/values/boolean/patch.xodp lib/awg/values/number/patch.xodp

.PHONY : doc
doc : README.md NODES.md

NODES.md : always
	script/doc lib/awg > $@
	markdown $@ > NODES.html

README.md : always
	@# for node documentation
	awk '/^# Nodes/ {print}; /^# Nodes/,/^# / {next}; {print}' $@ > tmp_README.md
	script/doc -n -h 3 lib/awg >> tmp_README.md
	mv tmp_README.md README.md
	markdown $@ > README.html

.PHONY : always
always :


lib/awg/values/boolean lib/awg/values/number :
	mkidr -p $@

lib/awg/values/boolean/any.cpp lib/awg/values/number/any.cpp : lib/awg/values/text/any.cpp
	echo "// Generated by makefile from $<" > $@
	echo >> $@
	cat $< >> $@
	sed -i "s/input_text/input_$(shell basename $(shell dirname $@))/g" $@
lib/awg/values/boolean/patch.xodp lib/awg/values/number/patch.xodp : lib/awg/values/text/patch.xodp
	cp $< $@
	@# we assume all text -> number
	sed -i 's/text/$(shell basename $(shell dirname $@))/g' $@
	sed -i "s/input-string/input-$(shell basename $(shell dirname $@))/g" $@
	sed -i "s/output-string/output-$(shell basename $(shell dirname $@))/g" $@



.PHONY : install
install :
	rm /home/$(USER)/xod/lib/awg 2>/dev/null || true
	ln -s `pwd`/lib/awg /home/$(USER)/xod/lib/awg

