workspace := ~/xod
# as of 0.15.0, it's __lib__ for user stuff
libdir := __lib__
userlib := $(workspace)/$libdir

.PHONY : all
all : lib2patch derive-values install doc

.PHONY : lib2patch
# link our lib's patch.xodp to project lib-edit, patch lib-x-x-x
# then we can edit it from xod
lib2patch :
	rm -rf $(workspace)/lib-edit/lib-*; cd lib; for p in `find . -name patch.xodp`; do n=`dirname $$p | sed 's/^\.\///; s/\//-/g'`; newdir=$(workspace)/lib-edit/lib-$$n; mkdir -p $$newdir && ln -s `pwd`/`dirname $$p`/patch.xodp $$newdir; done

.PHONY : derive-values
derive-values : lib/awg/values/boolean lib/awg/values/number lib/awg/values/boolean/any.cpp lib/awg/values/number/any.cpp lib/awg/values/boolean/patch.xodp lib/awg/values/number/patch.xodp lib/awg/values/boolean/patch.xodp lib/awg/values/number/patch.xodp

.PHONY : doc
doc : README.md NODES.md

NODES.md : always
	script/doc lib/awg > $@
	markdown $@ > NODES.html

XODNODES.md : always
	if [ -e xod-dev ]; then \
		script/doc -h 3 xod-dev/workspace/__lib__ > $@; \
		markdown $@ > XODNODES.html; \
	else \
		echo "Can't make $@, link 'xod-dev' to git checkout"; \
	fi

README.md : always
	@# for node documentation
	awk '/"auto generated below here"/ {print}; /"auto generated below here"/,/^# / {next}; {print}' $@ > tmp_README.md
	script/doc -n -h 3 lib/awg >> tmp_README.md
	mv tmp_README.md README.md
	markdown $@ > README.html

.PHONY : always
always :


lib/awg/values/boolean lib/awg/values/number :
	mkidr -p $@

lib/awg/values/boolean/any.cpp lib/awg/values/number/any.cpp : lib/awg/values/text/any.cpp
	echo "// Generated by makefile from $<" > $@
	echo >> $@
	cat $< >> $@
	sed -i "s/input_text/input_$(shell basename $(shell dirname $@))/g" $@
lib/awg/values/boolean/patch.xodp lib/awg/values/number/patch.xodp : lib/awg/values/text/patch.xodp
	cp $< $@
	@# we assume all text -> number
	sed -i 's/text/$(shell basename $(shell dirname $@))/g' $@
	sed -i "s/input-string/input-$(shell basename $(shell dirname $@))/g" $@
	sed -i "s/output-string/output-$(shell basename $(shell dirname $@))/g" $@



.PHONY : install
install :
	rm $(workspace)/lib/awg 2>/dev/null || true
	ln -s `pwd`/lib/awg $(workspace)/lib/awg

