
.PHONY : all
all : lib/awg/values/boolean lib/awg/values/number lib/awg/values/boolean/any.cpp lib/awg/values/number/any.cpp lib/awg/values/boolean/patch.xodp lib/awg/values/number/patch.xodp lib/awg/values/boolean/patch.xodp lib/awg/values/number/patch.xodp

lib/awg/values/boolean lib/awg/values/number :
	mkidr -p $@

lib/awg/values/boolean/any.cpp lib/awg/values/number/any.cpp : lib/awg/values/text/any.cpp
	echo "// Generated by makefile from $<" > $@
	echo >> $@
	cat $< >> $@
	sed -i "s/input_text/input_$(shell basename $(shell dirname $@))/g" $@
lib/awg/values/boolean/patch.xodp lib/awg/values/number/patch.xodp : lib/awg/values/text/patch.xodp
	cp $< $@
	@# we assume all text -> number
	sed -i 's/text/$(shell basename $(shell dirname $@))/g' $@
	sed -i "s/input-string/input-$(shell basename $(shell dirname $@))/g" $@
	sed -i "s/output-string/ouput-$(shell basename $(shell dirname $@))/g" $@



.PHONY : install
install :
	ln -s `pwd`/lib/awg /home/$(USER)/xod/lib/awg

